<a href="https://colab.research.google.com/github/JacksonLeb/tensorflow_learning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this notebook we will cover the fundamentals of tensors using tensorflow

More specifically, we are going to cover introduction to tensors, getting info from tensors, manipulating tensors and tensors and numpy. Additionally, we will be using tf.function and using GPUs with TensorFllw or (TPU).

## Introduction to Tensors

In [52]:
#import TensorFlow
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.8.2


In [3]:
# creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Checking the number of dimensions of a tensor
scalar.ndim

0

In [5]:
#creating a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
#Check the dimension of our vector
vector.ndim

1

In [7]:
#Create a matrix
matrix = tf.constant([[10, 7],[7,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
#create another matrix 
matrix2 = tf.constant([[10., 7.],
                       [3., 2.],
                       [8., 9.]], dtype=tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
#What's number of dimensions fo matrix2?
matrix.ndim

2

In [11]:
#creating a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],

                       [[7,8,9],
                        [10,11,12]],
                       
                       [[13,14,15],
                        [16,17,18]]])


In [12]:
tensor.ndim

3

In [13]:
# Create the same tensor with tf.Variable
changeable_tensor = tf.Variable([10,7])
constant_tensor = tf.constant([10,7])

changeable_tensor, constant_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
#cahnging element in chaneable
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
#creating random tensors
rand1 = tf.random.Generator.from_seed(42)
rand1 = rand1.normal(shape=(3,2))
rand1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [16]:
rand2 = tf.random.Generator.from_seed(7)
rand2 = rand2.normal(shape=(3,2))
rand2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [17]:
rand1 == rand2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

### Shuffling order of values in a tensor

In [18]:
#shuffling a tensor
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled.ndim

2

In [19]:
#suffle our tensor
shuffled = tf.random.shuffle(not_shuffled)
shuffled
shuffled.shape

TensorShape([3, 2])

In [20]:
shuffled = tf.random.shuffle(shuffled, seed=42)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [22]:
X = tf.zeros(shape=(3,2))
X

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [24]:
Y = tf.constant([[7,8],
                 [9, 10],
                 [11,12]])
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [30]:
Y = tf.reshape(Y, shape=(2, 3))
Y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [32]:
tf.transpose(Y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 10],
       [ 8, 11],
       [ 9, 12]], dtype=int32)>

In [39]:
tf.tensordot(tf.transpose(Y), Y, axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[149, 166, 183],
       [166, 185, 204],
       [183, 204, 225]], dtype=int32)>

In [41]:
#Changing the Datatype of different tensors (usually float32)
B = tf.constant([1.7, 9.8])
B.dtype


tf.float32

In [43]:
C = tf.constant([4,5])
C.dtype

tf.int32

In [45]:
#changing from float32 to float 16
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 9.8], dtype=float16)>

In [47]:
B = tf.cast(B, dtype=tf.int16)
B

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([1, 9], dtype=int16)>

#Aggregating Tensors

In [50]:
#Getting absolute values
E = tf.constant([-7, -10])
E = tf.abs(E)
E

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [57]:
np.random.randint(0, 101, size=100)
F = tf.constant(np.random.randint(0, 101, size=100))
F
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [62]:
tf.reduce_max(F)
tf.reduce_mean(F)
tf.reduce_sum(F)

<tf.Tensor: shape=(), dtype=int64, numpy=4773>

In [71]:
import tensorflow_probability as tfp
tfp.stats.variance(F)
F = tf.cast(F, dtype=tf.float32)
tf.math.reduce_std(F)

<tf.Tensor: shape=(), dtype=float32, numpy=27.97029>

#FInding positional max and min

In [74]:
tf.random.set_seed(20)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.78914285, 0.47340286, 0.39979064, 0.730348  , 0.65567374,
       0.95290804, 0.1569767 , 0.876413  , 0.42520928, 0.6074914 ,
       0.5420697 , 0.8619175 , 0.6087326 , 0.25354815, 0.02741039,
       0.807798  , 0.4440137 , 0.9375683 , 0.20025587, 0.9634783 ,
       0.8950304 , 0.56499386, 0.2593336 , 0.7975584 , 0.4932909 ,
       0.92441773, 0.26945102, 0.177073  , 0.35694516, 0.54103565,
       0.231601  , 0.71623254, 0.07930815, 0.59971976, 0.42030382,
       0.9922309 , 0.6451732 , 0.4512868 , 0.0813998 , 0.8110639 ,
       0.9847126 , 0.32717872, 0.94470954, 0.0367533 , 0.4858843 ,
       0.6560893 , 0.15126693, 0.7843076 , 0.50933826, 0.3634901 ],
      dtype=float32)>

In [76]:
#finding the positional maximum (argmax)
tf.argmax(F)


<tf.Tensor: shape=(), dtype=int64, numpy=35>

In [79]:
#index on our largest value positions
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9922309>

In [82]:
#finding the argmin and indexing on it
tf.argmin(F), F[tf.argmin(F)]

(<tf.Tensor: shape=(), dtype=int64, numpy=14>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.027410388>)

#Squeezing Tensors

In [86]:
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.56149936, 0.5322509 , 0.21349204, 0.14224744, 0.24900997,
           0.29649258, 0.5828576 , 0.87756705, 0.46964884, 0.49624312,
           0.347165  , 0.9002404 , 0.24888134, 0.13334143, 0.7932534 ,
           0.52148473, 0.7517016 , 0.08064973, 0.0479238 , 0.42142844,
           0.4269904 , 0.3398471 , 0.43957734, 0.3103615 , 0.6713376 ,
           0.21429396, 0.5751244 , 0.28973556, 0.57203245, 0.24918151,
           0.42484057, 0.93715453, 0.5289    , 0.41966426, 0.59873796,
           0.21750665, 0.65033257, 0.56693864, 0.24323165, 0.48032486,
           0.85055923, 0.23941374, 0.4313519 , 0.94459546, 0.98494124,
           0.3466432 , 0.7448336 , 0.64229167, 0.97319937, 0.0868541 ]]]]],
      dtype=float32)>

In [89]:
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [91]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.56149936, 0.5322509 , 0.21349204, 0.14224744, 0.24900997,
       0.29649258, 0.5828576 , 0.87756705, 0.46964884, 0.49624312,
       0.347165  , 0.9002404 , 0.24888134, 0.13334143, 0.7932534 ,
       0.52148473, 0.7517016 , 0.08064973, 0.0479238 , 0.42142844,
       0.4269904 , 0.3398471 , 0.43957734, 0.3103615 , 0.6713376 ,
       0.21429396, 0.5751244 , 0.28973556, 0.57203245, 0.24918151,
       0.42484057, 0.93715453, 0.5289    , 0.41966426, 0.59873796,
       0.21750665, 0.65033257, 0.56693864, 0.24323165, 0.48032486,
       0.85055923, 0.23941374, 0.4313519 , 0.94459546, 0.98494124,
       0.3466432 , 0.7448336 , 0.64229167, 0.97319937, 0.0868541 ],
      dtype=float32)>

###One-Hot encoding

In [96]:
#Creating a list of indices
some_list = [0, 1, 2, 3]

#one hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [98]:
tf.one_hot(some_list, depth=4, on_value="Yes", off_value="No")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yes', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No'],
       [b'No', b'No', b'No', b'Yes']], dtype=object)>

#More Tensorflow math problems
##Squaring, log, square root

In [100]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [101]:
tf.square(H)


<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [105]:
tf.math.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [108]:
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

#Tensorflow and Numpy arrays

In [111]:
#creating a tensor from numpy array
nparray = np.array([1,2,3,4])
J = tf.constant(nparray)
J

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [113]:
type(J)

tensorflow.python.framework.ops.EagerTensor

#One of the main difference between numpy array and tf tensor is tf tensor is better for GPU or TPU processing


In [1]:
tf.config.list_physical_devices()

NameError: ignored

In [3]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [5]:
!nvidia-smi

Mon Jun 20 20:55:20 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P8    10W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

#HOw to get tf code to run on GPU