<a href="https://colab.research.google.com/github/JacksonLeb/tensorflow_learning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this notebook we will cover the fundamentals of tensors using tensorflow

More specifically, we are going to cover introduction to tensors, getting info from tensors, manipulating tensors and tensors and numpy. Additionally, we will be using tf.function and using GPUs with TensorFllw or (TPU).

## Introduction to Tensors

In [2]:
#import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.8.2


In [4]:
# creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
# Checking the number of dimensions of a tensor
scalar.ndim

0

In [9]:
#creating a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [11]:
#Check the dimension of our vector
vector.ndim

1

In [15]:
#Create a matrix
matrix = tf.constant([[10, 7],[7,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [17]:
matrix.ndim

2

In [20]:
#create another matrix 
matrix2 = tf.constant([[10., 7.],
                       [3., 2.],
                       [8., 9.]], dtype=tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [22]:
#What's number of dimensions fo matrix2?
matrix.ndim

2

In [26]:
#creating a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],

                       [[7,8,9],
                        [10,11,12]],
                       
                       [[13,14,15],
                        [16,17,18]]])


In [28]:
tensor.ndim

3

In [30]:
# Create the same tensor with tf.Variable
changeable_tensor = tf.Variable([10,7])
constant_tensor = tf.constant([10,7])

changeable_tensor, constant_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [32]:
#cahnging element in chaneable
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [43]:
#creating random tensors
rand1 = tf.random.Generator.from_seed(42)
rand1 = rand1.normal(shape=(3,2))
rand1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [48]:
rand2 = tf.random.Generator.from_seed(7)
rand2 = rand2.normal(shape=(3,2))
rand2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [50]:
rand1 == rand2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

### Shuffling order of values in a tensor

In [52]:
#shuffling a tensor
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled.ndim

2

In [55]:
#suffle our tensor
shuffled = tf.random.shuffle(not_shuffled)
shuffled
shuffled.shape

TensorShape([3, 2])

In [61]:
shuffled = tf.random.shuffle(shuffled, seed=42)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [65]:
!git init
!git add .

Reinitialized existing Git repository in /content/.git/


In [70]:
!git config --global user.email "lebj@umich.edu"
!git config --global user.name "JacksonLeb"
!git branch -M main
!git commit -m "shuffling and initialization of different tensors"
!git push -u main

On branch main
nothing to commit, working tree clean
fatal: The current branch main has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream main main

